### ISSUE TITLE
Withings shim - not returning entire dataset for time range

### ISSUE THREAD

**Issue by nosh** [openmhealth/shimmer#21]
If I submit a query as follows:

`http://shimserver:8083/data/withings/body?username=nosh&dateStart=2015-01-01&dateEnd=2015-05-15&normalize=true`

I should get all readings from Jan 1, 2015 to May 15, 2015. However, I seem to get readings than span only about 2 months

If I then submit the query 

`http://shimserver:8083/data/withings/body?username=nosh&dateStart=2015-01-01&dateEnd=2015-02-15&normalize=true`

i.e. readings from Feb 15 to January 1, then I get some more readings (within the specified time range)- which shows that there are readings that were not retrieved by the first query, even though the time ranges overlap

Response from Emerson on mailing list:

--------
I've just checked the Withings shim, and it's passing those parameters to the Withings API verbatim. Some other shims truncate the range because of API limits, but the Withings shim isn't one of them.

re: pagination feedback, it doesn't look like Withings provides the 'more' value unless 'limit' is being used. But if we assume that "Results are always sorted from the most recent one first to the oldest one" is true even when not specifying a limit, you could theoretically ask for time ranges in reverse chronological order; make a call for a big range that ends now, then the next call's range would end at the time of the oldest data point in the first response. It's a hack, but could work.

The better way to fix this is to hook up the pagination information in ShimDataRequest to the Withings shim, and handling the 'more' response field

**Comment by emersonf** [comment]
Just a quick update that we're actively working on addressing pagination and related issues. Stay tuned.

**Comment by nosh** [comment]
This seems to be working now. I'm able to submit requests for ranges of data and shimmer returns me the expected data for the entire date range e.g.:  
http://omh-shimmer.datanosh.com:8083/data/withings/blood_pressure?username=nosh.petigara@gmail.com&dateStart=2015-01-01&dateEnd=2015-12-15&normalize=true

I'm not sure if this is because of some change you did in the shims or some changes in the Withings API - but this seems to work for me

**Comment by schaefba** [comment]
In release [v0.3.0](https://github.com/openmhealth/shimmer/releases/tag/v0.3.0), we removed the use of the Shimmer limit parameter (`numToReturn`) for body measure requests (see be32363). This had previously limited responses from the body measure endpoint to only 50 data points by default. The limit was not used with other endpoints, since no others support a limit query parameter. 

Because the Withings API does not limit the date range that can be requested from the body measures endpoint, the result of this change is that, for the body measures endpoint, there are no limits to the requests you are able to make of Shimmer for measures from that endpoint (which include weight, blood pressure, heart rate, and height). This explains the change in behavior you are seeing.

Unfortunately, Withings limits the number of days that you can request from other end points, which they describe at the very bottom of their [FAQ](http://oauth.withings.com/api/faq). Their documentation states that a maximum of 200 days of data will be returned by each request for daily activity and sleep summaries. Based on our testing, they will be the first 200 days of the request. And if you are using `partnerAccess` for intraday step count, you will be limited to a single day of data at a time, with their API returning the first day of your request.

This is currently a limitation of Shimmer and, as @emersonf mentioned, we are in the process of fixing the issue by using pagination and making multiple requests to third party APIs that span the entirety of the requests made of Shimmer. For the time being, we would recommend segmenting your Shimmer requests for steps and sleep into 200 day periods at a time (or a single day at a time if you are using intraday steps). 

**One more note:** We removed the use of the `numToReturn` legacy parameter from Withings, however it is still being used in Jawbone and Runkeeper. This potentially prevents Shimmer from fulfilling requests made for those APIs. We are working on removing this legacy parameter from those APIs and should be done shortly. Since your original issue was likely caused by this legacy parameter, we will keep it open until the fix is released.
