### ISSUE TITLE
Dockerfile still uses maven

### ISSUE THREAD

**Issue by jaredsieling** [openmhealth/shimmer#24]
It looks like Maven was abandoned for Gradle only, however, the Dockerfile still uses Maven, which gives an error when building the Docker image.

**Comment by emersonf** [comment]
Thanks for the bug report. I'll point the Dockerfile to Gradle later today.

In the next iteration, we'll leverage Docker Compose to assemble and link multiple containers instead of trying to shove these different processes into a single one. That would probably deprecate this build option entirely.

**Comment by emersonf** [comment]
I've updated the Docker build, but it can't get its hands on the HV SDK from CodePlex, and the authors of the SDK haven't released it to Maven Central or jCenter, even though the SDK itself is listed as Apache 2.0. I've reached out to them to see if we can get this sorted out.

Please upvote [this issue](https://healthvaultjavalib.codeplex.com/workitem/17470) to accelerate this.

**Comment by emersonf** [comment]
We've switched to Docker Compose in 0.3.0.
