### ISSUE TITLE
What's the security model of shimmer?

### ISSUE THREAD

**Issue by gcampax** [openmhealth/shimmer#28]
Hello!

I'm trying out shimmer locally, and I noticed that there seems to be no authorization on the /data request: once a the shim-server has acquired the OAuth access token for a given username, it will happily give out data to anyone who requests it.

This is perfectly fine if shimmer is meant to be used behind a closed firewall, so that only the real application server can touch shimmer. But that does not work if shimmer controls the OAuth authorization flow on its own: the user must be able to access the authorize callback with the browser.

This is also fine if the username is used as a secret bearer token. But the name username, and the fact it appears in plain in the URL suggests that it is not a secret value, and in the security model of the web I'm afraid it makes it more risky (for example, it becomes visible to Referrer headers).

So what's the expected security model? How should I configure shimmer in a way that noone can access data that it does not own in the first place?

**Comment by emersonf** [comment]
Ciao Giovanni. 

Shimmer is not designed to be exposed on the web, because as you said, there are no authorization checks to get data. The resource server is designed to be run within your own infrastructure, and accessed by your backend, in the same way that you'd deploy a database, an email server, or some other subsystem.

But as you said, Shimmer needs to be involved in the OAuth dance with a third-party API. Specifically, 

1. Shimmer needs to provide the URL of the third-party site to send the user to to get an authorization grant, called the *authorization URL*.
  * This authorization URL contains a query parameter called the *redirection URI*, which the third-party will redirect the user's browser to once the user completes the authorization grant.
  * The domain of the redirection URI is controlled by the `callbackUrlBase` property in the YAML configuration.
1. Shimmer needs to handle requests to that redirection URI, to extract the grant and exchange it for an access token.

re: point 1, the authorization URL is obtained by your application using the `/authorize/{shim}` endpoint. That call isn't initiated by the browser and so doesn't need to be exposed. 

re: point 2, the requests are handled by the `/authorize/{shim}/callback` endpoint and the call is initiated by the browser, so it needs to be reachable. However, it doesn't need to be exposed directly. Since the endpoint location is controlled by the `callbackUrlBase` property in Shimmer, it can be a URL to a proxy or to your application, not necessarily to Shimmer. You then just need to get this request forwarded to Shimmer.

We've typically done this using a reverse proxy like [nginx](https://hub.docker.com/_/nginx/). Here's an example configuration:

```Nginx
# forward redirects from third-party API to the shim server
location ~ /authorize/(.+)/callback {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://shimmer-resource-server:8083;
}
```

This effectively keeps Shimmer inside your infrastructure.

We know this design isn't the cleanest or most straightforward. We're currently focusing on making data retrievals more robust and expressive, but in a month or so, we plan to look at the authorization management aspects of Shimmer. That should include making these endpoints more clear, easier to use, improving token management, and possibly securing Shimmer itself using OAuth. If you have any feedback, please let us know. We'll try to keep everyone updated on progress on our [developer forum](https://groups.google.com/forum/#!forum/omh-developers).

PS. I'll add all this information to the README next week, but feel free to ask any further questions here.

**Comment by gcampax** [comment]
Would it not be easier to just handle the OAuth fully in the frontend, and pass the access token / refresh tokens to shimmer?
Especially in the case of Google, I already have code in the frontend to handle "login with Google", so it does not really help me to have Shimmer handle that part.

**Comment by emersonf** [comment]
A typical application that uses Shimmer doesn't have any third-party API authorization code of its own, but relies on Shimmer to handle authorization, including getting and refreshing access tokens. If we were to remove that functionality, people would have to implement the authorization from scratch for each API they want to use. Not only does that mean handling different authorization protocols (OAuth 1.0a, OAuth 2.0, and custom stuff), but also handling the nuances of each API, since very few APIs follow the specs verbatim. In your case, e.g., if you added support for Jawbone besides Google Fit, you'd have to learn and implement Jawbone's authorization mechanism. We want to avoid that to make Shimmer easy to use.

That being said, we do want to separate concerns. The current code couples data retrievals with authorization in ways we don't like. For example, it's possible for a data retrieval to trigger a token refresh. Once that's decoupled, it should be easier for somebody who already has OAuth 2.0 token management to use it and trigger only the data retrieval portion. For OAuth 1.0a, different data will need to be passed in to support signing, but the principle is the same.  So we'll be working on the decoupling first, and once that's done, we'll look into being able to support your use case or use cases where people are already using libraries like Scribe.

**Comment by emersonf** [comment]
If you have any other comments, feel free to add them here.
