### ISSUE TITLE
jawbone data not downloading

### ISSUE THREAD

**Issue by dchase73** [openmhealth/shimmer#35]
I get this error in the pop-up

Sorry, we are unable to process the request.

Error code: invalid_redirect

**Comment by emersonf** [comment]
This is caused by a misconfiguration of your application on the [Jawbone developer portal]("https://jawbone.com/up/developer").

The authorization sequence goes something like this...

1. Your application calls Shimmer to get an authorization URL for Jawbone.
1. Shimmer returns an authorization URL that contains a redirect URL query parameter like `redirectUrl=http://localhost:8083/authorize/jawbone/callback`.
  - The user's browser needs to be able to reach that redirect URL.
1. Your application sends the user's browser to the authorization URL, where they put in their credentials and authorize your application to access their data.
1. Jawbone redirects the user's browser to the redirect URL, **if it is listed in the *OAuth redirect URLs* configured in the portal, in the *Application Links* section.**

If the redirect URL isn't in that list, Jawbone shows the error you're seeing instead of redirecting.

If the redirect URL is missing from the developer portal list, add it to the list. If you need to control the URL, modify the `callbackUrlBase` property in Shimmer's `application.yaml`.

We're working on making the authorization flow smoother in future releases.

**Comment by vascoosx** [comment]
I think I read that the Jawbone redirect url **has to be** https.

**Comment by davidepiazza** [comment]
when running in local docker machine the console is exposed at http://localhost:8083 
But Jawbone says in the developer portal that: "You cannot publish your application with HTTP redirect URIs."
How is it possible to test the integration locally?

**Comment by emersonf** [comment]
The redirect used to hit our Docker containers just fine without TLS, but Jawbone may have made the redirect more restrictive to protect the response code. We'll experiment tomorrow and get back to you with our findings.

**Comment by vascoosx** [comment]
If you are using docker from a non-linux machine, register the container IP instead of localhost. It worked for me. 
Check the `redirect_uri` parameter to check the address being used.

**Comment by schaefba** [comment]
I tested this as well. It works for me by registering the container IP as one of the URLS in the `OAuth redirect URLs` list on the developer portal. They do state that you must use HTTPS, but this is not enforced as far as we can tell.

**Comment by davidepiazza** [comment]
Thank you Chris, indeed the https thing is not enforced. I assumed that remaining the jawbone in unpublished status the endpoint would not work, but it is working.
Thanks

**Comment by emersonf** [comment]
Glad to see this is working. I've added TLS support as a [separate issue](https://github.com/openmhealth/shimmer/issues/39).
