### ISSUE TITLE
Forbidden access while connecting Googlefit with console

### ISSUE THREAD

**Issue by steveck-chung** [openmhealth/shimmer#37]
Hi there,
I tried to setup the shim for some experiment and it's placed on AWS as docker. The console looks fine and credential was set, but the authorization process seems failed and the popup dialog showed:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Feb 19 10:55:17 UTC 2016
There was an unexpected error (type=Internal Server Error, status=500).
org.springframework.web.util.NestedServletException:
Request processing failed; nested exception is
org.springframework.web.client.HttpClientErrorException: 403 Forbidden
```

And [here](https://gist.github.com/steveck-chung/818d4cd0dffdc35d9ced) is the error log from resource server.

Is is possible that the credential was created with incorrect information, something missed while setting the resource server or any other step I ignored? Thanks.

**Comment by schaefba** [comment]
Hi there, could you provide us a little more detail about when exactly you are receiving the message? Do you see the Google account selection menu? Are you presented with the Google redirect requesting login information?

Do you receive it consistently? Do you receive it for all accounts or only some accounts? Hopefully a little more information can help us figure it out.

**Comment by StefanoWehmix** [comment]
Hello,
I have the same problem. I have created a project in console.developers.google.com and I put Client ID and Client secret in my Shimmer platform. When I try to connect Google fit account to Shimmer the popup with the authorization request is shown but If I click to Allow I have the same error of steveck-chung ("403 Forbidden").
I have tried with different account and different google project.
The strange thing is that I did the same steps two weeks ago and I had no problems. I then tried to update shimmer and now It doesn't work. I also tried to reset everything and install Shimmer old version (v0.4.2), but I have the same problem.
I'm using Mac OS.
What can I do?

Thanks

**Comment by abhishekab** [comment]
I receive the same error , while initiating an authorizing request for a new user. It goes to google account for authorization but as soon as I allow the access, the (403 Forbidden ) error shows up. If I again try to request the authorization for the same user, it doesnt even return an authorization url instead gives 403 error directly.

**Comment by emersonf** [comment]
Thanks for the information, we'll look into it again today.

I receive the same error , while initiating an authorizing request for a
new user. It goes to google account for authorization but as soon as I
allow the access, the (403 Forbidden ) error shows up. If I again try to
request the authorization for the same user, it doesnt even return an
authorization url instead gives 403 error directly.

—
Reply to this email directly or view it on GitHub
<https://github.com/openmhealth/shimmer/issues/37#issuecomment-194717947>.

**Comment by emersonf** [comment]
The error you're seeing is Google Fit sending a `403 Forbidden` when Shimmer requests data after an access token is obtained, at least according to that first log file @steveck-chung sent. Since that data retrieval request happens immediately, I was concerned there might be a race condition, but @abhishekab's note that subsequent calls give the same result makes it unlikely that this is a timing issue.

I've gone through a full sequence with a new project, and I can't replicate the problem. The following steps work for me

1. Go to the developer console
1. Create a new project
1. Enable the Fitness API

  ![screen shot 2016-03-10 at 14 14 43](https://cloud.githubusercontent.com/assets/834831/13672314/824089c0-e6d4-11e5-8025-a76970c5d590.png)

1. Create credentials

  ![screen shot 2016-03-10 at 14 15 01](https://cloud.githubusercontent.com/assets/834831/13672337/a0af4284-e6d4-11e5-832e-b64f57efdd94.png)
  ![screen shot 2016-03-10 at 14 15 42](https://cloud.githubusercontent.com/assets/834831/13672348/a8986c82-e6d4-11e5-8669-0c8050d22c3e.png)

1. Configure client credential restrictions

  ![screen shot 2016-03-10 at 15 28 25](https://cloud.githubusercontent.com/assets/834831/13672583/c2e0db96-e6d5-11e5-8e70-dc0bb579dc09.png)

  - The redirect URI domain `dev.docker.majezistix.com` is configured in my `/etc/hosts` file to point to my Docker machine (VirtualBox). The Compose file has its `OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE` environment variable set to  `http://dev.docker.majezistix.com:8083` as explained in issue #38.

1. Start new Docker containers
1. Visit the Shimmer console
1. Set the Google Fit credentials in the Shimmer console settings page
1. Connect a user
1. Get data

Since that vanilla approach works, I suggest you try two things. The first is to keep your client credentials intact and wipe the tokens (assuming you're dealing with a test environment). Assuming your MongoDB container is called `shimmer_mongo_1`

```
# docker exec -ti shimmer_mongo_1 mongo
> use omh_dsu
> db.authorizationRequestParameters.remove({});
> db.accessParameters.remove({});
> exit
```

If that doesn't work, I'd change the credentials. As a last resort, I'd bring up a new set of containers. 

Any feedback will help us diagnose further. We'll also do some work to improve logging and understand whether there's more information in the response from Google Fit, since we can't eliminate an issue on their side at this point either.

**Comment by abhishekab** [comment]
Changing the credentials worked for me. Dunno why. Thanks a lot :)
