### ISSUE TITLE
Connect Google FIT gives Error: invalid_request  device_id and device_name are required for private IP: 

### ISSUE THREAD

**Issue by davidepiazza** [openmhealth/shimmer#38]
Hi,
working from a local machine when I connect to google fit I get the error:
Error: invalid_request

device_id and device_name are required for private IP: http://192.168.99.101:8083/authorize/googlefit/callback

Am i doing something wrong?
thank you

**Comment by schaefba** [comment]
Hey there,

This is a known issue when working with Google APIs (see [here](http://stackoverflow.com/questions/24736168/error-invalid-request-device-id-and-device-name-are-required-for-private-ip)). Assuming that you are using docker, I believe most of the workarounds proposed in that post won't work since Shimmer sends the IP as the redirect, instead of a hostname. 

If you can run Shimmer natively, which we have provided instructions for, you can use localhost, which Google doesn't have an issue with. So running the application natively should fix this problem with Google Fit.  

Hope that helps! We'll look into whether there's anything we can do about the Docker container.

**Comment by StefanoWehmix** [comment]
Hi,
we found a workaround for this problem. During the installation we edited the script "update-compose-files.sh" before running it, replacing the placeholder for the IP ${IP} with a Hostname. 

`sed -i ".bak" -e "s,.*OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE.*,    OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE: http://wehmixshimmer.com:8083,g" docker-compose.yml
sed -i ".bak" -e "s,.*OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE.*,    OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE: http://wehmixshimmer.com:8083,g" docker-compose-build.yml`

The Hostname is  defined in the hosts file of the machine (in Mac: /private/etc/hosts). We associated it with the IP of the virtual machine running Docker. (in our case we add this line: "192.168.99.100  wehmixShimmer.com")

**Comment by emersonf** [comment]
There are a few things going on here.

1. Google wants the redirect URI to use a domain name with a real TLD. The Developer Console shows the following error when setting a redirect URI with an IP address.
*"Invalid Redirect: http://192.168.99.100:8083 must end with a public top-level domain (such as .com or .org)"*
1. The Developer Console does allow `http://localhost:8083`, even though that contradicts its warning. So there shouldn't be issues when running containers on Linux, but on Mac OS and Windows, the Docker host is in a separate VM and not on `localhost`.
1. You could use [xip.io](http://xip.io/) in the Developer Console and set the redirect URI to `http://192.168.99.100.xip.io:8083` which is a domain. But Docker machine IPs can change. If you restart a machine, `docker-machine` will warn you that *"Started machines may have new IP addresses. You may need to re-run the 'docker-machine env' command."* So that isn't a stable solution, because you'd have to go back to the Developer Console and add or change URIs if the IP changes.
1. The redirect URI that Shimmer sends to Google Fit (and every other integration) is fixed at load time. The `update-compose-files.sh` script uses `docker-machine ip` to set the redirect URI according to the current machine, i.e. the one pointed at by `DOCKER_*` environment variables from `docker-machine env`.

The stable solution to the problem is to give the Docker machine a hostname, as @StefanoWehmix suggested. So you have to pick a hostname. I'd suggest a hostname for each machine, e.g. `default.mydockermachine.com`, `dev.mydockermachine.com`, where the third-level domain corresponds to the `DOCKER_MACHINE_NAME` environment variable.

So you'd 

1. create a hostname per machine in your hosts file, e.g. `/private/etc/hosts` on OS X, pointing to the corresponding Docker machine IP
1. add redirect URIs to the Developer Console for each machine you intend to use
1. modify the `sed` lines in the `update-compose-files.sh` to use the hostname based on the current machine, e.g. `sed -i ".bak" -e "s,.*OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE.*, OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE: http://${DOCKER_MACHINE_NAME}.mydockermachine.com:8083,g" docker-compose-build.yml`

Should the machine IP change, you'd update the IP in your hosts file and things will keep working.

There's still too much hoop jumping for my liking, and it's partially due to the redirect URI being fixed at load time. We'd talked about parameterizing the redirect URI during authorization, but it always got postponed. I'll look into how much benefit that would give when we next revisit authorization.

**Comment by justinmeskan** [comment]
This question never mentioned Docker.. 

This is my error and i'm not using docker
Error 400: invalid_request
device_id and device_name are required for private IP: http://10.0.0.147:8888/auth/google/callback
Learn more

**Comment by tananga** [comment]
Any progress on this issue?
