### ISSUE TITLE
Issue in accessing Runkeepr data from omh

### ISSUE THREAD

**Issue by manihatv** [openmhealth/shimmer#50]
Hi, 

I have been trying to record the data captured with my Runkeeper application using the omh. Everything was working fine till today afternoon(02:00 PM EET, 25 May, 2016). And after that, when I tried to fetch the data using the omh dashboard, I am getting the error :  "Error, could not get data from server500" . 

I also tries accessing the data through URL from a custom built android application and I was not able to get the data as well. Is there any planned outage ? Is anybody else facing the same issue .?

**Comment by emersonf** [comment]
There should be logs recording the failure. Can you paste the part of yhe
logs which shows the error please?
On 25 May 2016 3:14 p.m., "manihatv" <notifications@github.com> wrote:

Hi,

I have been trying to record the data captured with my Runkeeper
application using the omh. Everything was working fine till today
afternoon(02:00 PM EET, 25 May, 2016). And after that, when I tried to
fetch the data using the omh dashboard, I am getting the error : "Error,
could not get data from server500" .

I also tries accessing the data through URL from a custom built android
application and I was not able to get the data as well. Is there any
planned outage ? Is anybody else facing the same issue .?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/openmhealth/shimmer/issues/50>

**Comment by manihatv** [comment]
Hi Emerson, 

I was held up with the issue for the past two hours. I tried restarting the docker machine and nothing was working out. 

But, I just tried accessing the site once after posting the issue here. And to my surprise, it started to work normally. Thank you so much for your time. 

Thanks.

**Comment by emersonf** [comment]
No problem, feel free to paste the logs all the same.
